### ISSUE TITLE
Compatibility with Thunderbird 78

### ISSUE THREAD

**Issue by xsistema** [lieser/dkim_verifier#199]
**There exist a 4.0.0 pre-release there the main verification already works in TB 78. It is available for download at https://github.com/lieser/dkim_verifier/releases**

The xpi can be downloaded under *Assets* at the bottom of each release.

Also note that the outdated Enigmail add-on can cause problems. Disable or remove the Enigmail add-on and restart Thunderbird to resolve this.

---

Installed today 3.1.0 version on TB 73.0b1. I see that add-on is installed - but on plugin manage page is just blank page. Also no action on TB mail panel - no text or menu available..

Error console messages:

```
ReferenceError: gDKIMOptionsGeneralPane is not defined options.xul:1:1
    onload chrome://dkim_verifier/content/options.xul:1
TypeError: textbox is null aboutAddonsExtra.js:44:25
    <anonymous> chrome://messenger/content/aboutAddonsExtra.js:44
SyntaxError: redeclaration of const THUNDERBIRD_THEME_PREVIEWS aboutAddonsExtra.js:1:1
```

**Comment by lieser** [comment]
Thanks a lot for reporting the problem. I will try to look into it this weekend, but can't promise anything.

**Comment by lieser** [comment]
Looks like TB removed the legacy XUL overlay loader this add-on still used. This mean the add-on needs to be converted into the new add-on type (MailExtensions). Which will probably not be something small.

I defiantly do plan to do this conversion into the new type. But you should not expect there to be a compatible version anytime soon.

**Comment by xsistema** [comment]
Don't let this great add-on die... Is there a big work involved due to TB change to version 75?

**Comment by lieser** [comment]
Like I said, I don't plan to let this add-on die, in fact I already started with the work a while ago.
Its just that this update will be something bigger. Especially since I'm trying to avoid any quick and dirty solutions, and instead invest more time to try improve the code quality while doing the update.

So unfortunately you will have to still wait some time. I will post here if there is a version ready there at least the basic works.

**Comment by lieser** [comment]
I have a very early version ready that you could start to try out: [dkim_verifier@pl.zip](https://github.com/lieser/dkim_verifier/files/4432707/dkim_verifier%40pl.zip)

Note that only the basic DKIM verification works for now. Nothing else.
The resolver used is JSDNS. If you need to change the DNS server, you must do that via Thunderbird's config editor (bool pref `extensions.dkim_verifier.dns.getNameserversFromOS` and string pref `extensions.dkim_verifier.dns.nameserver`).

**Comment by xsistema** [comment]
Super, I can confirm it's working on TB75.0b3 (64-bit) Win10.

**Comment by hiasl360** [comment]
With TB 76.0b1 (64-Bit) macOs Version 4.0.0pre0 is not working. I get the following error console message:

`Error: Incorrect argument types for dkimHeader.setDkimHeaderResult.`

**Comment by xsistema** [comment]
The same on Win10 TB 76.0b1 (64-Bit)..

**Comment by lieser** [comment]
Thanks for letting me know, already noticed it will I worked on the porting today. Here is a new version that should work with TB 76 [dkim_verifier@pl.zip](https://github.com/lieser/dkim_verifier/files/4500058/dkim_verifier%40pl.zip).

The version has the same limitations as the previous. Although the options page is now available again, the page doesn't work.

**Comment by xsistema** [comment]
Yes, it's working now on Win10 TB 76.0b1 (64-bit).

**Comment by lieser** [comment]
To lessen the amount of work needed for the migration of the add-on to a webextension, I'm thinking about dropping some features. If someone depends on any of the following, please let me know:
- account specific options
- showing the DKIM result in the status bar
- any of the add-ons hidden options, that can only be changed via TBs config editor

**Comment by xsistema** [comment]
I think most important is simply to see above the message DKIM test result (now it's working fine). Another good option would be to have an ability to create a filter - for example - From: ends with: ebay.com + DKIM is invalid (or missing) -> then: Move to Trash". I think these two options are the most important. Perhaps on mouse over warning icon (or OK icon - which does not exists yet) - would be nice to see more information, for example "Insecure signature algorithm: 2048 bits".

**Comment by DavidOsipov** [comment]
Also waiting to see the new version, that is compatible with Thunderbird 78

**Comment by lieser** [comment]
@DavidOsipov did you already try the last version I posted above?

I'm hoping to finish a new pre-release in the next few days, there at least most of the basic stuff and options work.
Unfortunately it will still take longer until the port to WebExtension is fully complete.

**Comment by DavidOsipov** [comment]
Thank you for your work! I installed it but my configuration of the Add-on is not being saved after I close the add-on configuration tab. 
BTW, can I just ignore installing libunbound files to the Thunderbird's extensions folder, if there a raspberry pi with unbound (maximum security + DNSSEC) + pi-hole (DNSSEC) in my local network?

**Comment by lieser** [comment]
I just published a new pre-release 4.0.0pre1 at https://github.com/lieser/dkim_verifier/releases. It still has some limitations (see release page), but it is a lot closer to the final state than the last version I uploaded here in this issue.

Please also start reporting and issues you see with with this verion (excluding the ones mentioned on the release page). Thanks.

@DavidOsipov 
> BTW, can I just ignore installing libunbound files to the Thunderbird's extensions folder, if there is a raspberry pi with unbound (maximum security + DNSSEC) + pi-hole (DNSSEC) in my local network?

Using the libunbound resolver needs a locally available libunbound library, regardless of the used DNS server.
But if you have a local DNSSEC aware server that you use as the DNS server, and you trust your local network (which I assume you do), you should be protected by DNSSEC with the default JSDNS resolver too.
You will however not get the DNSSEC indicator (https://github.com/lieser/dkim_verifier/wiki/Options#indicate-successful-dnssec-validation-with-a-lock-after-the-sdid) so see if the key was protected by DNSSEC.

Please create a separate issue if you have more questions about this.

**Comment by peci1** [comment]
I get this error with the prerelease version 4.0.0pre1 and TB 78.1.1:

```
aMsgHdr is null MimeMessage.jsm:185
    MsgHdrToMimeMessage resource:///modules/gloda/MimeMessage.jsm:185
    getFull chrome://messenger/content/parent/ext-messages.js:208
    getFull chrome://messenger/content/parent/ext-messages.js:206
    getFull self-hosted:844
    result resource://gre/modules/ExtensionParent.jsm:996
    withPendingBrowser resource://gre/modules/ExtensionParent.jsm:602
    result resource://gre/modules/ExtensionParent.jsm:996
    callAndLog resource://gre/modules/ExtensionParent.jsm:958
    recvAPICall resource://gre/modules/ExtensionParent.jsm:995
    AsyncFunctionNext self-hosted:693
DKIM_Verifier.background	FATAL	 Unexpected error during onMessageDisplayed Error: An unexpected error occurred background.mjs.js:169:7
    <anonymous> moz-extension://243dc715-800f-4257-9352-fded50b7a6b9/content/background.mjs.js:169
```

**Comment by lieser** [comment]
Thanks for the report, but I can not reproduce it. Can you please give more information?
E.g.:
- Does it happen with every email you view?
- Have you tried it with all other add-ons disabled?

Note that this could also be a potential bug in TB. This error seems to olny happen if `browser.messages.getFull(messageId)` gets called with an invalid `messageId`. But the id used by the add-on comes directly from TB itself.

**Comment by peci1** [comment]
I had the account set up to only download message headers. I've noticed the described error only happens with messages I downloaded during the current run of TB. If I download a message body and restart TB, switching to it doesn't generate any error. I've tried with all other addons off, and the behavior is the same.

**Comment by lieser** [comment]
Thanks for investigating the problem, with your info I could now reproduce it. Looks like a bug in TB to me, so I filled a bug for it: https://bugzilla.mozilla.org/show_bug.cgi?id=1659555. I also don't see an easy workaround, so lets hope it gets fixed quickly in TB itself.

**Comment by tranceptor** [comment]
Now this plugin is not compatible with the new 78.2.2 version of Thunderbird.
The plugin was automatically disabled.
Thank you.

**Comment by xsistema** [comment]
The 81.0b4 64-bit Win OS version is the newest now..

**Comment by hagedose** [comment]
> Now this plugin is not compatible with the new 78.2.2 version of Thunderbird.
> The plugin was automatically disabled.

4.0.0pre1 works for me with TB 78.2.2
Are you sure you have that?

**Comment by tranceptor** [comment]
> > Now this plugin is not compatible with the new 78.2.2 version of Thunderbird.
> > The plugin was automatically disabled.
> 
> 4.0.0pre1 works for me with TB 78.2.2
> Are you sure you have that?

I can't find this version from repository... Where can I download it from?

**Comment by lieser** [comment]
I just published a new pre-release 4.0.0pre2 at https://github.com/lieser/dkim_verifier/releases.

Changes since v4.0.0pre1:
- Saving of results works
- fixed verification messages using 8-bit encoding (#214)

The other limitations still apply, see also the release page.

@tranceptor Did you already go to the [releases page](https://github.com/lieser/dkim_verifier/releases.)?
The xpi can be downloaded under *Assets* at the bottom of each release.

I also updated the top post of this issue, to hopefully make it more obvious.

**Comment by xsistema** [comment]
Super, it's working fine. I would recommend to change default highlighting of From header background colors to about: 

Valid signature: #B9FFB9
Valid signature with warnings: #FFDF81
Invalid signature: #FFC6C6

A little bit softer colors looks better - and more convenient.

**Comment by xsistema** [comment]
Is it possible to add a DKIM filter option "invalid" (or "valid") to message filters? It is very important feature: [dialog image](https://www.xsistema.lt/file-manager/downloads/f879c86c-2872-4159-a6cd-9ae077a0c25f_TB%20filter.jpg)

**Comment by lieser** [comment]
Please keep this issue about the compatibility with TB 78, and related bugs.

For everything else, like your feature request, create a separate issue please.

**Comment by LeeThompson** [comment]
Stopped working with TB 78.3.1 after I updated today.

`DKIM Verifier is incompatible with Thunderbird 78.3.1.`

**Comment by jdreesen** [comment]
Did you try `4.0.0pre2`? It works for me.

**Comment by LeeThompson** [comment]
I have not tired 4.0.0pre2, I only use what's on the add-on thing.

**Comment by silvershadowcc** [comment]
Maybe release a 3.1.1 for the compatibility fix so people can keep using the addon until v4 is released?

**Comment by gene-git** [comment]
4.0.0pre2 + TB 78.3.2 - the header panel says: DKIM: internal error running on linux.
Anyone else seeing this?

thanks

**Comment by gene-git** [comment]
This seems to be a bug with TB - i notice that after it has been running a while the error occurs - at that point CardBook also fails to offer address completion - restarting thunderbird  clears the problem and both addons function normally again. sorry for noise.

**Comment by tobwen** [comment]
4.0.0pre2 works for me on 78.4.0 (32-Bit)

**Comment by lieser** [comment]
Took a while, but I just published a new pre-release 4.0.0pre3 at https://github.com/lieser/dkim_verifier/releases.

With sign rules now working (UI is still a little ugly in some places), this should be the last big feature that needed migration. The rest will hopefully go faster.

Changes since v4.0.0pre2:

- Sign rules now work (some limitations still apply)
- Fix parsing of from header (#218)

The other limitations still apply, see also the release page.

Note that I also decided to publish it to ATN, even if the migration is still not completely done.

**Comment by juvtib** [comment]
My Thunderbird updated automatically this afternoon. I'm getting a result in the message preview. 

![DKIM Verifier showing in Thunderbird 78.](https://i.imgur.com/qaiFzB0.png)

**Comment by leagris** [comment]
Only gives **`Internal Error`**:
Environment: Ubuntu Linux 20.10
Thunderbird: 78.3.2 (64-bits)
DKIM Verifier: 4.0.0pre3

Problem persist after restarting Thunderbird.

**Comment by gene-git** [comment]
Works fine for me with TB 78.4.3 and prev release 78.4.2 using TB using mozilla provided builds.
Im using Arch with kde plasma - fully updated.
Only other add-on i use is Cardbook - add-ons seem to be able to interfere with each other,  from what I've seen in the past.

But 4.0.0pre3 is working well for me.
I think there was a 'refresh' option at some point, but I don't seem to see that anymore?

**Comment by leagris** [comment]
Look like a problem with libunbound

**Comment by gene-git** [comment]
Interesting catch - I am also using the javascript lib for dns.

**Comment by lieser** [comment]
For me, libunbound works. Can you please enabled debug mode, and post the output of the error console or send it to me via e.mail? Thanks.

**Comment by leagris** [comment]
Here is the DEBUG log where it is erroring with `libunbound`:

Exactly at:
```debug
15:24:21,941 WebExtensions: libunboundWorker: Posting exception back to main script: TypeError: ub_ctx_delete is not a function; stack: load@chrome://dkim_verifier/content/libunboundWorker.jsm.js:293:16
onmessage@chrome://dkim_verifier/content/libunboundWorker.jsm.js:492:10
libunbound.js:234
```
https://gist.github.com/leagris/a1acb9cbdd4a6c8728e24efd0e275c0e#file-gistfile1-txt-L9-L11

**Comment by lieser** [comment]
My guess is that although the dll file you specify exist, it does not contain the required functions like `ub_ctx_delete`. I would expect you get already an error before the one you posted.

If the loading is successful, you should be able to see the following lines in the output:
```
DKIM_Verifier.dns	DEBUG	 configure libunbound dns.mjs.js:74:7
WebExtensions: libunboundWorker: loading libunbound: C:\<path to dll>/libDNSSECcore-windows-x86.dll libunbound.js:234
WebExtensions: libunboundWorker: libunbound loaded libunbound.js:234
WebExtensions: libunboundWorker: context created
```

Please double check that you specified the correct dll.

**Comment by leagris** [comment]
I don't have this in logs:

The configured path to `libunbound` is:
`/usr/lib/x86_64-linux-gnu/libunbound.so.8`
Relative is not checked

Here is what I have

```none
16:34:31,409 DKIM_Verifier.dns	DEBUG	 configure libunbound dns.mjs.js:74:7
16:34:31,415
Error in libunboundWorker: libunboundWorker: TypeError: ub_ctx_delete is not a function; subType: DKIM_DNSERROR_UNKNOWN; stack: load@chrome://dkim_verifier/content/libunboundWorker.jsm.js:293:16
onmessage@chrome://dkim_verifier/content/libunboundWorker.jsm.js:492:10
libunbound.js:251
    _onmessage jar:file:///home/lea/.thunderbird/of2ck7z5.Nouveau Profil/extensions/dkim_verifier@pl.xpi!/experiments/libunbound.js:251
    onmessage jar:file:///home/lea/.thunderbird/of2ck7z5.Nouveau Profil/extensions/dkim_verifier@pl.xpi!/experiments/libunbound.js:89
16:34:31,417
DKIM_Verifier.Verifier	FATAL	 Error: An unexpected error occurred
```

**Comment by lieser** [comment]
Note that the actually loading of the library (i.e. `libunboundWorker: loading libunbound` and `libunboundWorker: libunbound loaded` in the output) only happens at the first time libunbound is tried to be use, or the libunbound path/name is changed.
Could you please restart Thunderbird, and look at the output of the first tried verification?

I assume the shared lib was installed through the package manager? Then it should definitely have the functions in it. But you could still do a double check if you want (https://stackoverflow.com/questions/34732/how-do-i-list-the-symbols-in-a-so-file).

Is the Thunderbird you are running also 64-bit or 32-bit? If it is 32-bit, trying to load an 64-bit library could explain the issue.

Currently don't have a Linux there I can test this myself. But will try to do text this next week, if you haven't found the problem till then.

**Comment by gene-git** [comment]
I will try unbound on linux today. 

I did notice something odd reading the email notices from this thread - the mail from Léa via githib shows as DKIM: Valid (signed by github) while yours, Philippe, do not show anything at all - the mail headers confirm both do pass and are both signed by same githib s=pf2014 cert - the server header lines show dkim does pass authentication.

I have the option:  Read Authentication-Results header turned on.

Bit strange no. I have not seen, rather noticed, any other emails which are dkim pass but dkim_verifier is not showing that other than the ones from you Philippe ... almost amusing right!!

**Comment by gene-git** [comment]
Tested libunbound on linux with TB 78.4.3 
   - works fine.
When I turn this option on it shows path:
    _extensions/dnssec@nic.cz/plugins/ub_ds_windows-x86.dll_
which looks like a strange -  best I can tell there is no file anywhere on my system with the name ub_ds_xxx 
so perhaps that is not a file? or perhaps its not used on linux - i do have 
    _/usr/lib/libunbound.so_
which came from the unbound backage installed on the system.

best
gene

**Comment by gene-git** [comment]
Léa - perhaps a silly question - do you have unbound installed?

Probably not important, but my version is 1.11.0

gene

**Comment by gene-git** [comment]
Lea - I have unbound 1.11.0 and this shows:

objdump --dynamic-syms /usr/lib/libunbound.so | grep ub_ctx_delete

I wonder if the path in dkim_verifier is relevant - I did not change mine from default, odd as it looks, and yet it works.

**Comment by gene-git** [comment]
Seems some tests above ere not right.
Seems I had to change to libunbound and then restart TB otherwise the change may not be properly active  - after doing that the path to libunbound is empty - i put in /usr/lib/libunbound.so.

Still works for me though.

I have tried with and without:  Verify DKIM signatures (what does actually do?)
and combined with and without Read Authentication-Results header:
and all cases work for me.
 also tested with and without Get DNS servers from OS configuration.

**Comment by leagris** [comment]
Running Thunderbird 78.3.2 (64 bits)
libunbound8: /usr/lib/x86_64-linux-gnu/libunbound.so.8
[Gist of logs](https://gist.github.com/leagris/d18ab36cd38c2fe6f7495c686f893ead) from DKIM Verifier on restarting Tunderbird and up to first verification

```sh
objdump --dynamic-syms /usr/lib/x86_64-linux-gnu/libunbound.so.8 | grep -F ub_ctx_delete
000000000000c950 g    DF .text	0000000000000660  Base        ub_ctx_delete
```

**Comment by gene-git** [comment]
I also notie that even tho 'show favicon' is not selected, it does show for github but not other domains.
This is independent of javascript vs unbound.

Also note that in the 'display' settings - with or without highlighting selected there is no way to choose the highlighting for each of the 5 items. Highlihting is happening however as From headers are highlighted green when verified.

**Comment by gene-git** [comment]
Lea - clearly your unbound library is fine.
I wonder if these are relevant in your log: 
   Skipping migration of preferences as browser.storage ...
   Error: An unexpected error occurred options.mjs.js
   ... syntax error. errno: ...

I wonder if there is a way to clear things out, perhaps uninstall and reinstall dkim_verifier, and start fresh?

**Comment by lieser** [comment]
@leagris 
Is the following in the output you posted:
```
Error: error in ub_ctx_set_fwd: syntax error.
```
Seems like the DNS server you specified are in a format libunbound does not like. Are you perhaps specifying a port? Found out that libunbound does not support that (still need to document this). Can you post that you have specified there?
But I'm currently unable to explain how this could lead to the follow up errors you saw.

@gene-git I am unable to reproduce the errors your reported about options not behaving correctly.

Note that currently the options tab of the add-on is broken if you leave it open and restart Thunderbird. This is there the `Error: An unexpected error occurred options.mjs.js` errors are coming from.
For it to work, one has to close and repoen it, or right click and reload.

**Comment by leagris** [comment]
Uninstalled the extension.
Restarted Thunderbird first time
Restarted Thunderbird second time
Installed `dkim_verifier-4.0.0pre3-tb.xpi` sha512 `b839a6de26d700b83c51b6fb067578bff1171a13ed82a875d476de342053bb4e1f32db8dd6f6a3a3051763e343c1db0272887d2d3eaac6f15f4043eafad339c9`
Restarted Thunderbird third time

Checked what it has about the extension's config:

```sh
fgrep -iF dkim prefs.js
```
```js
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.dkim_verifier@pl", true);
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"1f71b305-a31a-4bd8-a024-f9a3f4098729\",\"default-theme@mozilla.org\":\"1d00c50f-ed10-4457-a94b-850134e372a2\",\"google@search.mozilla.org\":\"6f29bc4c-cd7e-4206-b3c8-a3cb99d51f1e\",\"bing@search.mozilla.org\":\"21f39fc3-b4a7-47b1-8b9a-e4b186473d56\",\"amazon@search.mozilla.org\":\"ecdddd1e-d292-4e77-b7c9-957a68d28dfc\",\"ddg@search.mozilla.org\":\"7ee1a87e-8a35-4d22-aeab-900a04a9100f\",\"qwant@search.mozilla.org\":\"8d080c12-cfff-4a82-aa8a-8abf56954aea\",\"wikipedia@search.mozilla.org\":\"380b4847-f2c2-4b06-b06d-9dc4f8007905\",\"{847b3a00-7ab1-11d4-8f02-006008948af5}\":\"1c071ce5-c7f1-4490-93a0-9306a2a0b1e4\",\"twitter@search.mozilla.org\":\"30ffe187-02ea-493b-b24b-09e4e22b6dd6\",\"tbsortfolders@xulforum.org\":\"96e92e98-f3fa-4a60-ab46-4155e2a5a12a\",\"sieve@mozdev.org\":\"69603ef0-5039-46dd-bb0f-1dd669d4c7d6\",\"signal-spam@signal-spam.fr\":\"92029b95-16d5-486b-a06c-355e4f797dde\",\"dkim_verifier@pl\":\"f272842c-b57a-4909-aa63-c29391782b83\"}");
```
Nothing except registration of it:

Going to dkim_verifier's preferences:

Switching to DNS/libunbound: it has these default settings:
![image](https://user-images.githubusercontent.com/1111474/99192444-2fb44e00-2773-11eb-8d4b-3345ca96ebfd.png)

The default libunbound path is: `extensions/dnssec@nic.cz/plugins/ub_ds_windows-x86.dll`

Does not make sense and is inappropriate with Linux though.

Change this to `/usr/lib/x86_64-linux-gnu/libunbound.so.8` and uncheck the relative path.

Still nothing new into prefs.js. So it look like dkim_verifier stores its preferences somewhere obscure place instead of the usual prefs.js keys extensions.extensionname.foo.bar.baz ...

Still same issue with libunbound

**Comment by leagris** [comment]
Ok finally found the culprit. And thank for your clue about the DNS ost:

I was using `localhost` as the DNS host and it did not please.

Now I have `::1` and it works with libunbound.
Although I'd expect it would understand the `[::1]` syntax for IPv6 host IP notation.

I'd say the EBNF syntax `(EBNF) : host[":"port]{";"host[":"port]}` from the preferences panel is not very straightforward about how to specify the host.

I'd suggest instead: `(EBNF) : ip[":"port]{";"ip[":"port]}`

**Comment by gene-git** [comment]
Glad you figured it out - and the difference between our settings for which I use: 
    Get DNS servers from OS configuration, but also had 1.1.1.1 
enjoy rest of weekend.

**Comment by lieser** [comment]
> Still nothing new into prefs.js. So it look like dkim_verifier stores its preferences somewhere obscure place instead of the usual prefs.js keys extensions.extensionname.foo.bar.baz ...

Yes, this is no longer used, as it is not directly usable by WebExtensions (same as in Friefox). It uses [browser.storage.local](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local) instead.
One important difference to keep in mind is that the storage (and therefore also preferences or user sign rules) will get cleaned if the add-on gets uninstalled.
The same will be true for majority of the other add-ons that work with the new TB.

About the EBNF syntax:
For JSDNS resolver, I would expect localhost to also work. And the port sntax works there too.
But agree, for libunbound it is currently confusing. Have to think about how to improve that.

For now, I at least updated the wiki to include this.

**Comment by yethie** [comment]
Hi, I installed the 4.0.0pre3 release and I'm getting the following error when verifying the Google DKIM signature for play console reviews messages:

```
DKIM_Verifier.background	FATAL	 Unexpected error during onMessageDisplayed InternalError: too much recursion
    parseFromHeader moz-extension://941aebbc-04ed-4fff-bb58-360f833be8d3/modules/msgParser.mjs.js:154
    verify moz-extension://941aebbc-04ed-4fff-bb58-360f833be8d3/modules/AuthVerifier.mjs.js:121
```

**Comment by lieser** [comment]
@yethie Thanks for reporting. Can you please post the From header of the affected e-mail, so I can reproduce and fix it? Thanks.

**Comment by gene-git** [comment]
Another one - my TB just updated to 78.5.0 - linux.
After restarting TB, all  dkim_veriifer settings were lost / reset to default - had to start fresh.

**Comment by yethie** [comment]
> @yethie Thanks for reporting. Can you please post the From header of the affected e-mail, so I can reproduce and fix it? Thanks.

@lieser this is the From field:

`
From: noreply-play-developer-console@google.com
`

Thanks for this useful tool!

**Comment by lieser** [comment]
@yethie the `too much recursion` issue should be fixed now. Fi will be included in the next version, which I probably will release this weekend.

@gene-git 
- Did you already hat previously the old 3.x version installed, with some settings set? If yes, did the settings get again successfully migrated?
- Do you also have aver add-ons installed? If yes which ones? And did they suffer the same issue?

To me this currently sound like a potential bug in how the update process of TB works for your Linux distribution. If other add-ons who also use the [browser.storage.local](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local) are also affected, this would confirm it.

**Comment by gene-git** [comment]
Hiya - 
- The version installed prior to TB update was 4.0.0pre3 - no change to that.
- Cardbook is only other add-on. I did not see any issues with cardbook.
- Options tab was indeed an open tab. The 3 TB tabs were:  Inbox,  Add-Ons Manager, DkimVerifier Options.

**Comment by lieser** [comment]
@gene-git Regarding my first question. I mean did you use the same profile also already for TB 68, and did you have the add-on there installed to?
If yes, and you did already change settings of the add-on in TB 68, your Thunderbird profile should have still setting in about config like `extensions.dkim_verifier.*`, even if the add-on is no longer actively using them.

But even if `browser.storage.local` for some reason got cleared during the update, this old setting should then have been migrated again.

Looked at Cardbook seems to still use the old way for saving settings. So no indicator if it is a problem with the add-on or a general issue with `browser.storage.local`

**Comment by gene-git** [comment]
When I was using TB-68 I was using whatever the most recent version was at the time - pretty sure  it was 4.0.0pre1 - around mid summer this year.  

When updated from 68 to TB 78.x i was already using 4.0.0preX. 

I changed the settings last few days to explore libunbound as per above discussion - that was TB 78.4 with 4.0.0pre3.
After that I exited and restarted TB to move to 78.5 - that's when I noticed the settings I just did (like libunbound etc) all went away.

I will exit and restart TB to see if they are retained. 
Does ti matter if the dkim_verifier options tab is  open or not?

**Comment by gene-git** [comment]
With Inbox tab selected - and dkim_verifier options tab the 3rd tab. Restarting TB causes all dk_ver options to be wiped.

**Comment by gene-git** [comment]
so sure looks like as of now, the settings are lost whenever TB is restarted.
Sorry, I didn't respond to your 68- 78 profile question - yes same TB profile.

**Comment by lieser** [comment]
@gene-git with "wiped", do you mean all checkbox are unselected? Like I wrote above somewhere, the options window is currently broken directly after restart if it was open. If you just close it and open it again, the settings should show again.

Can you confirm this?

**Comment by gene-git** [comment]
Bah - I missed the close/open options tab - yes - indeed that is the issue - close/open and all settings are now shown correctly.
Sorry for not following the issue ... sorry for noise.

**Comment by lieser** [comment]
No trouble, with the amount of messages here already, it's easy to miss some. And hope to be able to solve the displaying issue with the options in the next release, to avoid any further issues with that.

**Comment by gene-git** [comment]
thank you Philippe. have good weekend

**Comment by lieser** [comment]
Published a new 4.0.0pre4 pre-release at https://github.com/lieser/dkim_verifier/releases and ATN. Mostly bug fixes, and a few smaller updates/improvements.

**Changes since v4.0.0pre3:**

- libunbound resolver: Don't provide a default path
- libunbound resolver: Improve options description
- Sign rules: Special treatment of outgoing messages now supported
- Fixed relaxed ARH parsing option
- Fixed backtracking issues in parsing of from header, resulting in `InternalError: too much recursion`
- Fixed options page not correctly working if it was already open on start
- Added about page in options
- Updated default rules and favicons

**Comment by gene-git** [comment]
Thank you Philippe - working fine.

Have you considered adding dkim_verifier to the TB 'tools->Addon Options' menu?

**Comment by lieser** [comment]
> Have you considered adding dkim_verifier to the TB 'tools->Addon Options' menu?

I considered it briefly, but so far decided against it so far. I thing there should be a unified approach in TB how add-on options are opened, and that is also handled by TB itself, instead of each add-on doing it's own thing. And for TB 78, that is through the add-on manager.

**Comment by lieser** [comment]
Question to all who used the key storing feature:
Did you use the creation and last used date that could be seen then viewing the keys for anything?
If yes, please let me know, as I'm considering to remove this to keep thinks more simple.

**Comment by leagris** [comment]
- DKIM_Verifier 4.0.0pre4
- Thunderbird 78.5.0 (64 bits) Ubuntu Linux 20.10

Issue encountered:
- Internal Error

`background.mjs.js:164:7`
```none
DKIM_Verifier.background	FATAL	 Unexpected error during onMessageDisplayed Error: An unexpected error occurred
```

**Comment by lieser** [comment]
@leagris Thanks for reporting the error. Did you have debug enabled, and also saved the messages before the error? 
And can you reproduce the issue?
If not, I unfortunately don't think I will be able to find the underlying issue (and fix it). This kind of errors sadly don't provide any information at all by them self.

**Comment by Railander** [comment]
i know i'm very late to this, but it's sad to see that the status bar icon was scrapped.
i find that the other options are too intrusive, either by reducing normal TB functionality or adding to visual polution.

i'd love to see the icon come back even if next to the "From" header, similar to the well-known signer Favicon icon, which speaking of also hasn't worked for me since the TB update that broke the add-on.

**Comment by lieser** [comment]
@Railander I created the separated issue #237 for re-adding the status bar icon. But don't expect this to some back unless there will be more requesting this, as it currently it is very low on my to long priority list.

Regarding the Favicon icon, are you sure you have enabled the option, and are viewing a mail of one of the supported domains for this (https://github.com/lieser/dkim_verifier/blob/master/data/favicon.json)? This should work in TB 78 too.

If not, please disable all other add-ons, restart TB and try again. Maybe there is an incompatibility with another add-on.

**Comment by lieser** [comment]
Attached is a test version for people affected by recently fixed bugs. The storing of DKIM keys is also migrated in this.
[dkim_verifier-4.0.0pre4.1.zip](https://github.com/lieser/dkim_verifier/files/5939075/dkim_verifier-4.0.0pre4.1.zip)

**Comment by Railander** [comment]
> @Railander I created the separated issue #237 for re-adding the status bar icon. But don't expect this to some back unless there will be more requesting this, as it currently it is very low on my to long priority list.
> 
> Regarding the Favicon icon, are you sure you have enabled the option, and are viewing a mail of one of the supported domains for this (https://github.com/lieser/dkim_verifier/blob/master/data/favicon.json)? This should work in TB 78 too.
> 
> If not, please disable all other add-ons, restart TB and try again. Maybe there is an incompatibility with another add-on.

i understand the status bar might be more involving, i'd be fine even if the ball icon was readded in the "From:" header instead of color filtering the text or background.

regarding the favicon, it's always been enabled (just double-checked) and at some point it stopped showing. for example, our corporate domain uses g-suite and it did show the favicon back then but no longer does.

**Comment by lieser** [comment]
>regarding the favicon, it's always been enabled (just double-checked) and at some point it stopped showing. for example, our corporate domain uses g-suite and it did show the favicon back then but no longer does.

Did you look if the signing domain appears in the list I linked to? Maybe the domain changed, at least i can't remember that I removed a google related domain from it.

To debug the problem, please:
- Look in Thunderbird's error console if there is an error shown
- Try it with different mails that should be in the list, e.g. GitHub notifications (note that you need to enable [*Still verify the signature, if a domain is only testing DKIM*](https://github.com/lieser/dkim_verifier/wiki/Options#still-verify-the-signature-if-a-domain-is-only-testing-dkim) in advanced options), Amazon, PayPal
- Send me an affected mail as a saved eml file to lieser+dkim@posteo.net

**Comment by lieser** [comment]
@peci1 Note that your issue with only downloading the message headers (https://bugzilla.mozilla.org/show_bug.cgi?id=1659555) seems to be fixed in the latest daily. Don't know then it will be fixed in the normal release of Thunderbird.

**Comment by peci1** [comment]
> @peci1 Note that your issue with only downloading the message headers (https://bugzilla.mozilla.org/show_bug.cgi?id=1659555) seems to be fixed in the latest daily. Don't know then it will be fixed in the normal release of Thunderbird.

Thanks for letting me know!

**Comment by lieser** [comment]
Good news, the conversion to an MailExtension is finally completed. I will still do some testing, and probably release the final 4.0.0 version next weekend. If you want to already try it out, attached is the current state.
Please report any issues you may still encounter.

[dkim_verifier-4.0.0pre4.2.zip](https://github.com/lieser/dkim_verifier/files/6292863/dkim_verifier-4.0.0pre4.2.zip)

**Comment by gene-git** [comment]
Great thank you Philippe - working fine so far in 78.9.1

**Comment by gene-git** [comment]
One comment - the DKIM button in the header row on right.

My theme is dark them - the button is in dark them but clicking it brings up white background with 4 buttons.
First button (revirfify) has black background with white text - it looks great.
The other 3 buttons have white text on light gray background (hard to read) and all 4 items sit on a white backrgound.

I'd say change the white bg which holds the 4 buttons to something from dark palette - like the rest of TB when in dark theme.
Add more contrast to the 3 grayed out buttons.

Best

gene

**Comment by lieser** [comment]
Thanks for reporting the issue with the dark theme. Just tried the one built into TB (on Windows), and although it looks bad and definitely needs improvements, it does not look like what you described. Will look into it next week.

![grafik](https://user-images.githubusercontent.com/4419226/114325670-dc2b0e00-9b20-11eb-85e7-6d96dba06282.png)

Note that the difference in the buttons you descibe is probably from most of the buttons being disabled. They only get enabled if the action actually makes sense for the currently viewed mail and the configured options.

**Comment by gene-git** [comment]
kde plasma in dark theme. Yours looks worse lol ... 
Understand only enabled when appropriate ... anyway this is what it looks like on my setup.

![image](https://user-images.githubusercontent.com/17962808/114326232-d6720000-9b01-11eb-93a9-dceb9c59625c.png)

**Comment by gene-git** [comment]
Bigger issue to me is the white background.
The disabled text just needs a tad more contrast (more white less gray maybe).

**Comment by gene-git** [comment]
And these are really minor issues - the important stuff is the functionality and thats working great - thank you!

**Comment by lieser** [comment]
@gene-git The dark theme issue should be fixed. Can you please try out the attached version? Thanks.
[dkim_verifier-4.0.0pre4.3.zip](https://github.com/lieser/dkim_verifier/files/6330135/dkim_verifier-4.0.0pre4.3.zip)

**Comment by gene-git** [comment]
Yes - confirmed - it looks fine now - thank you!

**Comment by gene-git** [comment]
![image](https://user-images.githubusercontent.com/17962808/115128329-08c0a900-9fab-11eb-8713-dd7f42b78750.png)

**Comment by lieser** [comment]
Took a lot longer than I initially hoped for, but with the release of [version 4.0.0](https://github.com/lieser/dkim_verifier/releases/tag/v4.0.0) I did just now the migration is finally over. On ATN it is still under review, and should show up in the next couple of days.

Thanks a lot to all of your for your patience, and reporting any bugs you found during the process.
If you find any new Problems, please create a separate issue instead of using this one.

**Comment by gene-git** [comment]
thank *you* ... :)
